parameters:
    MIGRATIONS_SUB_DIR_NAME: 'default-%env(key:scheme:url:DATABASE_URL)%'

doctrine:
    dbal:
        schema_filter: '~^(?!(messenger_.*))~'
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: 'App\Infrastructure\Doctrine\Type\Core\UuidType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: App
