#!/bin/bash
set -e

DB_APP_PASSWORD=$(cat "$DB_APP_PASSWORD_FILE")

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${DB_APP_USER} WITH PASSWORD '${DB_APP_PASSWORD}';
    CREATE DATABASE ${DB_APP_DATABASE};
    GRANT ALL PRIVILEGES ON DATABASE ${DB_APP_DATABASE} TO ${DB_APP_USER};

    CREATE EXTENSION tsm_system_rows;
EOSQL
